apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bonqefe6t-go
  janus-idp.io/tekton: bonqefe6t-go
  backstage.io/kubernetes-id: bonqefe6t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bonqefe6t-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
